### ISSUE TITLE
Questions about the Behavior Learning of the DLC algorithm and `use_ego_color` in this repo

### ISSUE THREAD

**Issue by lkwq007** [igilitschenski/multi_car_racing#2]
Thanks for sharing this competitive environment. 

I am trying to implement the Deep Latent Competition algorithm, and I find that the description of Behavior Learning might be kind of confusing. 

![image](https://user-images.githubusercontent.com/1665437/100882202-dfb2e680-34e9-11eb-901e-6606c1fff0a0.png)

> This process leverages imagined trajectories `(s1,s2,a1,a2)` over a horizon of H starting from each timestep t within the sampled batch sequence, where **opponent behavior is estimated by querying the action model with predicted latent viewpoints**. The resulting algorithm optimizes policies by back-propagating analytic value gradients of imagined self-play trajectories through the learned multi-agent world model.

Figure 2(b) seems to suggest that the behavior optimization is conducted on the true states `s1`, `s2` (starting from the ground truth observations of both agents) and actions `a1`, `a2` based on these states and the policy. I was wondering where the estimated opponent behavior and predicted latent viewpoints are used in this Behavior Learning process. It seems that the encoders are not involved in the middle of the imagined trajectories, and the predicted latent viewpoints are not involved too. 

Besides, have you evaluated the DLC with `use_ego_color=True`? With `use_ego_color=True`, it seems that both agents can share the encoder model, observation model, and reward model. 
In contrast, which model can be shared by two agents when `use_ego_color=False`? Are these two agents using the independent encoder models, observation models, and reward models when `use_ego_color=False`? 

Thank you.

**Comment by igilitschenski** [comment]
> I was wondering where the estimated opponent behavior and predicted latent viewpoints are used in this Behavior Learning process.

They are not used in the behavior learning part. By training to predict the opponent's views, we ensure that the latent state has useful information about the opponent. 

> Are these two agents using the independent encoder models, observation models, and reward models when use_ego_color=False?

Agents share the encoder model, the observation model, and the reward model. This works even if `use_ego_color=False`, which is what we did in our experiments

**Comment by lkwq007** [comment]
Thank you for your explanation. Seems that I misunderstood this non-defining relative clause: `where opponent behavior is estimated by querying the action model with predicted latent viewpoints`

By the way, the idea of predicting the opponent's view is interesting, it indeed functions as an information bridge for opponent behavior estimation which the players would unconsciously do in real racing games.
