### ISSUE TITLE
Issue with starting and simulation

### ISSUE THREAD

**Issue by woosuk1103** [igilitschenski/multi_car_racing#4]
Hello, I'm learning reinforcement learning now and would like to conduct multi agent car racing RL simulation 
using your code. 

It seems that your code is well-constructed and easy to understand, but I'm new to here, so have several questions now.

1. To run the multi-agent car racing simulation with any RL code, is it okay to just place the RL code within the same folder that multi_car_racing.py is in? 

2. To make connection with environment you gave and "my_policy" code(e.g. action = my_policy(obs) in Readme.md),
how can I know the shape of "env" and build the RL code?

Any kind of advice will be appreciated.
Thanks in advance, 

Woosuk

**Comment by igilitschenski** [comment]
> To run the multi-agent car racing simulation with any RL code, is it okay to just place the RL code within the same folder that multi_car_racing.py is in?

You probably can, but this should not be necessary if you follow the [installation instructions](https://github.com/igilitschenski/multi_car_racing#installation).

> To make connection with environment you gave and "my_policy" code(e.g. action = my_policy(obs) in Readme.md),
> how can I know the shape of "env" and build the RL code?

In my example, `env` is an environment object and does not have a shape.
